package ventanas;
/*
import beans.Caja;
import beans.Facturapropiedades;
import beans.IngresosEgresos;
import beans.Movimientoscaja;
import interfaces.Buscadores;
import java.awt.Frame;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import managers.ManejadorConfiguraciones;
import managers.ManejadorDocumentos;
import managers.Model;

public class Formulario_Egresos_Ingresos extends javax.swing.JDialog {

    /** Creates new form Formulario_Egresos_Ingresos *
    ManejadorDocumentos md;
    ManejadorConfiguraciones mc;
    Model m;
    IngresosEgresos ie;
    Buscadores bu;
    Frame parent;
    int funcion = 0;

    public Formulario_Egresos_Ingresos(java.awt.Frame parent, boolean modal, Buscadores bu, Model m) {

        super(parent, modal);
        this.parent = parent;
        this.m = m;
        md = new ManejadorDocumentos(m);
        mc = new ManejadorConfiguraciones(m);
        this.bu = bu;
        ie = new IngresosEgresos();
        initComponents();
        utilidades.FormatoNumeros fn = new utilidades.FormatoNumeros(pagacon);
        pagacon.addKeyListener(fn);
        pagacon.addFocusListener(fn);

        fn = new utilidades.FormatoNumeros(devuelve);
        devuelve.addKeyListener(fn);
        devuelve.addFocusListener(fn);

        fn = new utilidades.FormatoNumeros(valor);
        valor.addKeyListener(fn);
        valor.addFocusListener(fn);

        int ano = Calendar.getInstance().get(Calendar.YEAR);
        int mes = Calendar.getInstance().get(Calendar.MONTH) + 1;
        int dia = Calendar.getInstance().get(Calendar.DATE);

        fecha.setText(ano + "-" + mes + "-" + dia);
        Facturapropiedades fp = mc.getFacturaporpiedades("1");

        ie.setNumero((fp.getEgresos() + 1) + "");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public Formulario_Egresos_Ingresos(java.awt.Frame parent, boolean modal, Buscadores bu, Model m, IngresosEgresos ie) {

        super(parent, modal);
        this.parent = parent;
        this.m = m;
        md = new ManejadorDocumentos(m);
        mc = new ManejadorConfiguraciones(m);
        this.bu = bu;
        this.ie = ie;
        initComponents();

        llenar();
        utilidades.FormatoNumeros fn = new utilidades.FormatoNumeros(pagacon);
        pagacon.addKeyListener(fn);
        pagacon.addFocusListener(fn);

        fn = new utilidades.FormatoNumeros(devuelve);
        devuelve.addKeyListener(fn);
        devuelve.addFocusListener(fn);

        fn = new utilidades.FormatoNumeros(valor);
        valor.addKeyListener(fn);
        valor.addFocusListener(fn);

        int ano = Calendar.getInstance().get(Calendar.YEAR);
        int mes = Calendar.getInstance().get(Calendar.MONTH) + 1;
        int dia = Calendar.getInstance().get(Calendar.DATE);

        fecha.setText(ano + "-" + mes + "-" + dia);
        Facturapropiedades fp = mc.getFacturaporpiedades("1");
        numero.setText("" + (fp.getPrefacturas() + 1));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void llenar() {
        guardar.setEnabled(false);
        funcion = 1;
        tipo.setSelectedIndex(ie.getTipo());
        concepto.setText(ie.getConcepto());
        tercero.setText(ie.getTerceros().getNit() + "");
        ntercero.setText(ie.getTerceros().getNombre());
        tipoc.setSelectedIndex(ie.getTipoconcepto());
        valor.setText(utilidades.FormatoNumeros.formatear(ie.getValor() + ""));
        numero.setText(ie.getNumero());
        fecha.setText(new java.text.SimpleDateFormat("yyyy-MM-dd").format(ie.getFecha()));
        pagacon.setEnabled(false);
        valor.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        buscaproveedor = new javax.swing.JButton();
        ntercero = new javax.swing.JTextField();
        tercero = new javax.swing.JTextField();
        et = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        pagacon = new javax.swing.JTextField();
        devuelve = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tipoc = new javax.swing.JComboBox();
        concepto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(212, 233, 255));

        jLabel1.setText("Recibo de ");

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingreso", "Egreso", " " }));
        tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoItemStateChanged(evt);
            }
        });

        jLabel2.setText("Numero");

        numero.setEditable(false);
        numero.setText("0");

        jLabel3.setText("Fecha");

        fecha.setEditable(false);

        buscaproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-16x16.png"))); // NOI18N
        buscaproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaproveedorActionPerformed(evt);
            }
        });

        ntercero.setEditable(false);

        tercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terceroActionPerformed(evt);
            }
        });

        et.setText("Recibido de");

        guardar.setBackground(new java.awt.Color(0, 153, 255));
        guardar.setFont(new java.awt.Font("Tahoma", 1, 11));
        guardar.setForeground(new java.awt.Color(0, 51, 153));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(0, 153, 255));
        salir.setFont(new java.awt.Font("Tahoma", 1, 11));
        salir.setForeground(new java.awt.Color(0, 51, 153));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bulletCritical.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        imprimir.setBackground(new java.awt.Color(0, 153, 255));
        imprimir.setFont(new java.awt.Font("Tahoma", 1, 11));
        imprimir.setForeground(new java.awt.Color(0, 51, 153));
        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print-16x16.png"))); // NOI18N
        imprimir.setText("Imprimir");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        pagacon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pagacon.setText("0.00");
        pagacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagaconActionPerformed(evt);
            }
        });
        pagacon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pagaconKeyReleased(evt);
            }
        });

        devuelve.setEditable(false);
        devuelve.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        devuelve.setText("0.00");

        jLabel7.setText("Devolver");

        jLabel6.setText("Paga con");

        jLabel4.setText("Concepto");

        tipoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Otros Ingresos" }));
        tipoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipocItemStateChanged(evt);
            }
        });

        concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conceptoActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor a pagar");

        valor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valor.setText("0.00");
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buscaproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(et))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tercero, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(concepto, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ntercero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(valor)
                        .addComponent(pagacon, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addComponent(devuelve, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tercero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(et)
                            .addComponent(ntercero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buscaproveedor)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pagacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(devuelve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir)
                    .addComponent(imprimir)
                    .addComponent(guardar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaproveedorActionPerformed
        // TODO add your handling code here:
        ie.setTerceros(new BuscaTerceros(parent, true, m).getTercero());
        if (ie.getTerceros() != null) {
            tercero.setText(ie.getTerceros().getNit() + "");
            ntercero.setText(ie.getTerceros().getNombre());
            concepto.requestFocus();
        }
}//GEN-LAST:event_buscaproveedorActionPerformed

    private void terceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terceroActionPerformed
        // TODO add your handling code here:
        if (tercero.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite el nit del Tercero ");
        } else if (md.getTercero((Object) tercero.getText()) != null) {
            ie.setTerceros(md.getTercero((Object) tercero.getText()));
            tercero.setText(ie.getTerceros().getNit() + "");
            ntercero.setText(ie.getTerceros().getNombre());

            concepto.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Tercero no existe");
        }
}//GEN-LAST:event_terceroActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //   tab.remove(dp);
}//GEN-LAST:event_salirActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
       
}//GEN-LAST:event_imprimirActionPerformed

    private void pagaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagaconActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            guardar();
        }
}//GEN-LAST:event_pagaconActionPerformed

    public void guardar() {
        Facturapropiedades fp = mc.getFacturaporpiedades("1");

        ie.setNumero((fp.getEgresos() + 1) + "");
        ie.setConcepto(concepto.getText());
        ie.setTipo(tipo.getSelectedIndex());
        ie.setValor(Double.parseDouble(valor.getText().replaceAll(",", "")));
        ie.setTipoconcepto(tipoc.getSelectedIndex());
        ie.setFecha(new Date(fecha.getText().replaceAll("-", "/")));
        md.crear(ie);
        bu.buscar();
        Caja caja = md.getCaja();
        if (ie.getTipo() == 0) {
            // caja.set
        }

        Movimientoscaja mcaja = new Movimientoscaja();
        mcaja.setCaja(caja);
        mcaja.setConcepto(tipo.getSelectedItem() + " " + concepto.getText());
        mcaja.setDoc(ie.getNumero() + "");
        mcaja.setTercero(ntercero.getText());
        mcaja.setTipo(ie.getTipo());
        mcaja.setValor(ie.getValor());
        md.crear(mcaja);

        this.dispose();
        JOptionPane.showMessageDialog(null, "Registro Exitoso");
    }

    public boolean validar() {
        if (numero.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite el NUMERO porfavor");
            numero.requestFocus();
            return false;
        } else if (fecha.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite la FECHA porfavor");
            fecha.requestFocus();
            return false;
        } else if (tercero.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite el PROVEEDOR porfavor");
            tercero.requestFocus();
            return false;
        } else if (concepto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite el Concepto porfavor");
            concepto.requestFocus();
            return false;
        } else if (valor.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite el valor porfavor");
            concepto.requestFocus();
            return false;
        } else if (Double.parseDouble(valor.getText().replaceAll(",", "")) <= 0) {
            JOptionPane.showMessageDialog(null, "Digite el valor porfavor");
            concepto.requestFocus();
            return false;
        }
        return true;
    }

    private void pagaconKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagaconKeyReleased
        // TODO add your handling code here:
        if (!pagacon.getText().trim().equals("")) {
            double t = Double.parseDouble(valor.getText().replaceAll(",", ""));
            //  if(Double.parseDouble(pagacon.getText().replaceAll(",",""))>=t){
            double dev = Double.parseDouble(pagacon.getText().replaceAll(",", "")) - t;
            devuelve.setText(utilidades.FormatoNumeros.formatear(dev + ""));
            //}
        }
}//GEN-LAST:event_pagaconKeyReleased

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
        pagacon.requestFocus();
    }//GEN-LAST:event_valorActionPerformed

    private void conceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conceptoActionPerformed
        // TODO add your handling code here:
        valor.requestFocus();
    }//GEN-LAST:event_conceptoActionPerformed

    private void tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoItemStateChanged
        // TODO add your handling code here:
        if (tipo.getSelectedIndex() == 0) {
            et.setText("Recibido de de");
            tipoc.removeAllItems();
            tipoc.addItem("Otros Ingreso");
        } else {
            tipoc.removeAllItems();
            tipoc.addItem("Gastos varios");
            tipoc.addItem("Retiros de Caja");
            et.setText("Pagado de");
        }
    }//GEN-LAST:event_tipoItemStateChanged

    private void tipocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipocItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscaproveedor;
    private javax.swing.JTextField concepto;
    private javax.swing.JTextField devuelve;
    private javax.swing.JLabel et;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField ntercero;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField pagacon;
    private javax.swing.JButton salir;
    private javax.swing.JTextField tercero;
    private javax.swing.JComboBox tipo;
    private javax.swing.JComboBox tipoc;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
*/